package top.yumbo.excel.util.constants;

public enum CellStyleEnum {
    FONT_NAME, FONT_SIZE, BG_COLOR, TEXT_ALIGN, LOCKED, HIDDEN, BOLD,
    VERTICAL_ALIGN, WRAP_TEXT, STYLES,
    FORE_COLOR, ROTATION, FILL_PATTERN, AUTO_SHRINK, TOP, BOTTOM, LEFT, RIGHT
}