package top.yumbo.excel.util.constants;

public enum CellEnum {
    TITLE_NAME, FIELD_NAME, SPLIT_REGEX, REPLACE_ALL, REPLACE_ALL_TYPE, FIELD_TYPE,
    SIZE, PATTERN, NULLABLE, WIDTH, JOIN, EXCEPTION, COL, ROW, SPLIT,
    PRIORITY, FORMAT, MAP_ENTRIES, MAP, POSITION_TITLE, OFFSET,TITLE_SPLIT
}
