package top.yumbo.excel.util.constants;

public enum TableEnum {
    WORK_BOOK, SHEET, TITLE_MAP, TABLE_NAME, TABLE_HEADER, TABLE_HEADER_HEIGHT,
    RESOURCE, TYPE, TABLE_BODY, PASSWORD, RECORD_ALL_EXCEPTIONS,
    LIMIT_ROW_EXCEPTION, REVERSE_MAP, TITLE_CACHE
}